---
- name: Deploy and manage ID Card application
  hosts: web
  become: true

  vars:
    app_dir: /app
    backup_dir: /backup
    db_name: "A-SAN_Meyhieng-db"        # change to your group-name-db
    db_user: root
    db_password: "Hello@123"
    db_host: "db"                         # docker-compose service name
    git_repo: "https://github.com/Meyhieng/Final-Devops.git"

  tasks:

    - name: Gathering Facts
      setup:

    - name: Reset any local git changes
      command: git checkout -- .
      args:
        chdir: "{{ app_dir }}"
      ignore_errors: true

    - name: Git pull latest code
      git:
        repo: "{{ git_repo }}"
        dest: "{{ app_dir }}"
        version: main
        force: yes

    - name: Fix mvnw permission
      file:
        path: "{{ app_dir }}/mvnw"
        mode: '0755'

    - name: Build using Maven
      command: ./mvnw package -DskipTests -Dspring.profiles.active=docker
      args:
        chdir: "{{ app_dir }}"

    - name: Run tests with SQLite
      command: >
        ./mvnw test
        -Dspring.datasource.url=jdbc:sqlite:./test.db
        -Dspring.datasource.driver-class-name=org.sqlite.JDBC
        -Dspring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
        -Dspring.jpa.hibernate.ddl-auto=create-drop
      args:
        chdir: "{{ app_dir }}"

    - name: Create backup directory
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'

    - name: Backup MySQL database
      shell: >
        mysqldump -h {{ db_host }} -u {{ db_user }} -p{{ db_password }}
        {{ db_name }} > {{ backup_dir }}/backup_$(date +%Y%m%d_%H%M%S).sql
      ignore_errors: true

    - name: Restart Spring Boot app (via docker-compose)
      command: docker-compose restart web-server
      args:
        chdir: "{{ app_dir }}/.."
      ignore_errors: true